---
- name: Check if OS is supported
  fail:
    msg: "OS not supported for BigBlueButton installation"
  when: ansible_distribution != "Ubuntu" or ansible_distribution_version != "{{ bbb_ubuntu_version }}"

- name: Enable https support for apt
  apt:
    name: apt-transport-https
    state: present
  tags:
    - apt_transport_https

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - update_apt_cache

- name: Install BigBluebutton required packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - software-properties-common
  tags:
    - bbb-dependencies

- name: Check python-apt is present
  apt: name=python-apt state=present
  tags:
    - bbb-role_dependencies

- name: Update locale (ensure LANG=en_US.UTF-8)
  lineinfile: dest=/etc/default/locale regexp=^LANG line='LANG=en_US.UTF-8'
  tags:
    - set_locale

- name: Update locale (ensure LC_ALL is absent)
  lineinfile: dest=/etc/default/locale regexp=^LC_ALL state=absent
  tags:
    - set_locale

- name: Check BigBlueButton apt key is present
  apt_key:
    url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
    state: present
  tags:
    - bbb-apt_key

- name: Check multiverse apt repositories are enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
  tags:
    - multiverse_repositories
    - repositories

- name: Check BigBlueButton repo is enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb {{ bbb_apt_repo_url }} bigbluebutton-xenial main'
  tags:
    - bbb-repositories
    - repositories

- name: Check BigBlueButton is installed
  apt: name=bigbluebutton state=present
  tags:
    - install_bbb

- name: Install bbb-demo package
  apt: name=bbb-demo state=present
  when: bbb_install_demo == True
  tags:
    - install_bbb-demo

- name: Install bbb-check package
  apt: name=bbb-check state=present
  when: bbb_install_check == True
  tags:
    - install_bbb-check

- name: Set BigBlueButton server name
  command: bbb-conf --setip "{{ bbb_server_name }}"
  tags:
    - run_bbb-conf_setip

- name: Restart BigBlueButton
  command: bbb-conf --restart
  tags:
    - bbb-restart

- name: Check BigBlueButton installation
  command: bbb-conf --check
  register: bbb_check_out
  tags:
    - bbb-check_install
- name: bbb-conf --check output
  debug: msg="{{ bbb_check_out }}"
  tags:
    - bbb-check_install
