---
- name: Update apt cache
  apt: update_cache=yes
  tags:
    - update_apt_cache

- name: BigBluebutton required packages are present
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - software-properties-common
  tags:
    - bbb_dependencies

- name: apt_repository required packages are present
  apt: name={{ item }} state=present
  with_items:
    - python-apt
  tags:
    - bbb_role_dependencies

- name: Update locale (ensure LANG=en_US.UTF-8)
  lineinfile: dest=/etc/default/locale regexp=^LANG line='LANG=en_US.UTF-8'
  tags:
    - set_locale

- name: Update locale (ensure LC_ALL is absent)
  lineinfile: dest=/etc/default/locale regexp=^LC_ALL state=absent
  tags:
    - set_locale

- name: BigBlueButton apt key is present
  apt_key:
    url: http://ubuntu.bigbluebutton.org/bigbluebutton.asc
    id: 328BD16D
    state: present
  tags:
    - bbb_apt_key

- name: multiverse apt repositories are enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu trusty multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu trusty multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu trusty-updates multiverse'
  tags:
    - multiverse_repositories

- name: libreoffice ppa is enabled
  apt_repository: repo='ppa:libreoffice/libreoffice-4-4'
  tags:
    - libreoffice_repositories

- name: ffmpeg ppa is enabled
  apt_repository: repo='ppa:mc3man/trusty-media'
  tags:
    - ffmpeg_repositories

- name: BigBlueButton repo is enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://ubuntu.bigbluebutton.org/trusty-1-0/ bigbluebutton-trusty main'
  tags:
    - bbb_repositories

- name: Install bigbluebutton
  apt: name={{ item }} state=present
  with_items:
    - bigbluebutton
    - bbb-demo
    - bbb-check

